export interface Child {
    id:string,
    childName:string,
    age:number,
    gender:string,
    dateOfAdmission:Date,
    SHM_NO:string,
    district:string
    taluk:string,
    address:string,
    anganwadiName:string,
    awAshaName:string,
    motherName:string,
    motherAge:number,
    motherEducation:string,
    motherProfession:string,
    fatherName:string,
    fatherAge:string,
    fatherEducation:string,
    fatherProfession:string,
    noOfFamilyMembers:number,
    averageDailyIncome:number,
    noOfSiblings:number,

}